### ISSUE TITLE
Document Settings Edit

### ISSUE THREAD

**Issue by JPBetley** [fatiherikli/dbpatterns#19]
Clicking the Edit Gear icon to edit a doc's settings causes another dialog to popup, but with incomplete properties, as some are added to the original dialog box. Selecting the edit icon multiple times, creates more dialogs with the same issue.

![before](https://f.cloud.github.com/assets/719517/962762/918bdccc-04f5-11e3-9ade-fd0240fc49b0.PNG)
![after](https://f.cloud.github.com/assets/719517/962763/918ae90c-04f5-11e3-967f-3ede2c006dd1.PNG)

**Comment by bahattincinic** [comment]
Fixed.
