### ISSUE TITLE
UI: Improvement for deleting attributes

### ISSUE THREAD

**Issue by Ryel** [fatiherikli/dbpatterns#36]
It's really unclear that this dot will delete an attribute.
My suggestion is to make it a more obvious icon like a red 'x' for example.

<img width="232" alt="screenshot 2016-04-14 15 30 08" src="https://cloud.githubusercontent.com/assets/4242005/14541012/d017e886-0255-11e6-9aea-8ae1acece93f.png">

**Comment by bahattincinic** [comment]
Fixed.
